#import "../../../../../gql/fragments/proposal-type.gql"

query ReportTurnover {
    reportTurnover {
        report {
            totalAmount
            data {
                date
                count
                dayAmount
                transactions {
                    key
                    proposal {
                        ...proposalType
                    }
                    id
                    amount
                    proposalId
                }
                key
            }
        }
    }
}
